version: "3"

services:
  # Equivalent command from the cli would look like this
  # $ docker container run --rm -itd -p 6379:6379 --name redis --network web2_default -v web2_redis:/data redis:3.2-alpine
  redis:
    image: "redis:3.2-alpine"
    ports:
      - "6379:6379"
    volumes:
      - "redis:/data"

  # Equivalent docker command from the cli would look like this
  # $ docker container run --rm -itd -p 5000:5000 -e FLASK_APP=app.py -e FLASK_DEBUG=1 --name web2 -v $PWD:/app --network web2_default
  web:
    # Looks for 'Dockerfile' in the current directory
    build: .
    # Compose will use image property value as the final name, can be used to have Compose build registry friendly tags
    #images: 'rnella01/web:1.0.0'

    # will ensure 'redis' container is started before starting the 'web' container
    depends_on:
      - "redis"
    # Enviroment variables can be provided in-line like below, but is preferred to be provided via .env file(s)
    #environment:
    #FLASK_DEBUG: "true"
    env_file:
      - ".env"
      # This will load the properties from .env.prod on top of thise from .env
      #- ".env.prod"
    # The ports exposed should match the one in 'Dockerfile': CMD flask run --host=0.0.0.0 --port=5000
    ports:
      - "5000:5000"
    volumes:
      - ".:/app"

volumes:
  redis: {}
